[font]
  size = 16
  normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
  bold = {family = "JetBrains Mono", style = "Bold"}
  italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
  bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
