[window]
  padding = { x = 5, y = 5 }

[font]
  size = 18
  normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
  bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
  italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
  bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
  offset = {x = 1, y = 0}
  glyph_offset = {x = 0, y = 0}
